primitives = [
	"usize",
	"isize",
	"f32",
	"f64",
	"u128",
	"u64",
	"u32",
	"u16",
	"u8",
	"i128",
	"i64",
	"i32",
	"i16",
	"i8",
	"String",
	"bool",
]

## BEVY_UI

[[types]]
type = "AlignContent"
source = "bevy_ui"

[[types]]
type = "AlignItems"
source = "bevy_ui"

[[types]]
type = "AlignSelf"
source = "bevy_ui"

[[types]]
type = "Direction"
source = "bevy_ui"

[[types]]
type = "FlexDirection"
source = "bevy_ui"

[[types]]
type = "FlexWrap"
source = "bevy_ui"

[[types]]
type = "FocusPolicy"
source = "bevy_ui"

[[types]]
type = "Interaction"
source = "bevy_ui"

[[types]]
type = "JustifyContent"
source = "bevy_ui"

[[types]]
type = "Overflow"
source = "bevy_ui"

[[types]]
type = "PositionType"
source = "bevy_ui"

[[types]]
type = "Val"
source = "bevy_ui"

[[types]]
type = "CalculatedClip"
source = "bevy_ui"

[[types]]
type = "Node"
source = "bevy_ui"

[[types]]
type = "Style"
source = "bevy_ui"

[[types]]
type = "UiImage"
source = "bevy_ui"

[[types]]
type = "Button"
source = "bevy_ui"

[[types]]
type = "Display"
source = "bevy_ui"


## BEVY_ANIMATION

[[types]]
type = "AnimationPlayer"
source = "bevy_animation"


## BEVY_CORE

[[types]]
type = "Name"
source = "bevy_core"


# ## BEVY_GLTF

[[types]]
type = "GltfExtras"
source = "bevy_gltf"


## BEVY_HIERARCHY

[[types]]
type = "Children"
source = "bevy_hierarchy"

[[types]]
type = "Parent"
source = "bevy_hierarchy"

## BEVY_TEXT

[[types]]
type = "Text2dBounds"
source = "bevy_text"

[[types]]
type = "Text"
source = "bevy_text"

[[types]]
type = "TextAlignment"
source = "bevy_text"

[[types]]
type = "TextSection"
source = "bevy_text"

[[types]]
type = "TextStyle"
source = "bevy_text"

## BEVY_TIME

[[types]]
type = "Stopwatch"
source = "bevy_time"

[[types]]
type = "Timer"
source = "bevy_time"


## BEVY_UTILS

# [[types]]
# type="Duration"
# source="bevy_utils"


# ## BEVY_REFLECT

# [[types]]
# type="DynamicArray"
# source="bevy_reflect"

# [[types]]
# type="DynamicList"
# source="bevy_reflect"

# [[types]]
# type="DynamicMap"
# source="bevy_reflect"

# [[types]]
# type="DynamicStruct"
# source="bevy_reflect"

# [[types]]
# type="DynamicTuple"
# source="bevy_reflect"

# [[types]]
# type="DynamicTupleStruct"
# source="bevy_reflect"


## BEVY_ECS 
[[types]]
type = "Entity"
source = "bevy_ecs"

## BEVY_TRANSFORM

[[types]]
type = "Transform"
source = "bevy_transform"

[[types]]
type = "GlobalTransform"
source = "bevy_transform"

## BEVY_PBR

[[types]]
type = "AmbientLight"
source = "bevy_pbr"

[[types]]
type = "CubemapVisibleEntities"
source = "bevy_pbr"

[[types]]
type = "DirectionalLight"
source = "bevy_pbr"

[[types]]
type = "DirectionalLightShadowMap"
source = "bevy_pbr"

[[types]]
type = "NotShadowCaster"
source = "bevy_pbr"

[[types]]
type = "NotShadowReceiver"
source = "bevy_pbr"

[[types]]
type = "PointLight"
source = "bevy_pbr"

[[types]]
type = "PointLightShadowMap"
source = "bevy_pbr"


[[types]]
type = "AlphaMode"
source = "bevy_pbr"

[[types]]
type = "Wireframe"
source = "bevy_pbr"

[[types]]
type = "WireframeConfig"
source = "bevy_pbr"

## BEVY_CORE_PIPELINE

[[types]]
type = "Camera3dDepthLoadOp"
source = "bevy_core_pipeline"


[[types]]
type = "ClearColor"
source = "bevy_core_pipeline"

[[types]]
type = "ClearColorConfig"
source = "bevy_core_pipeline"

[[types]]
type = "Camera2d"
source = "bevy_core_pipeline"

[[types]]
type = "Camera3d"
source = "bevy_core_pipeline"

## BEVY_SPRITE

[[types]]
type = "Anchor"
source = "bevy_sprite"

[[types]]
type = "Mesh2dHandle"
source = "bevy_sprite"

[[types]]
type = "TextureAtlasSprite"
source = "bevy_sprite"


[[types]]
type = "Sprite"
source = "bevy_sprite"


## BEVY_RENDER

[[types]]
type = "RenderLayers"
source = "bevy_render"

[[types]]
type = "Visibility"
source = "bevy_render"

[[types]]
type = "VisibleEntities"
source = "bevy_render"

[[types]]
type = "ComputedVisibility"
source = "bevy_render"

[[types]]
type = "SkinnedMesh"
source = "bevy_render"

[[types]]
type = "ScalingMode"
source = "bevy_render"

[[types]]
type = "Color"
source = "bevy_render"

[[types]]
type = "Aabb"
source = "bevy_render"

[[types]]
type = "CubemapFrusta"
source = "bevy_render"

[[types]]
type = "Frustum"
source = "bevy_render"

[[types]]
type = "Msaa"
source = "bevy_render"

[[types]]
type = "Camera"
source = "bevy_render"

[[types]]
type = "RenderTarget"
source = "bevy_render"

[[types]]
type = "Viewport"
source = "bevy_render"


[[types]]
type = "Projection"
source = "bevy_render"

[[types]]
type = "OrthographicProjection"
source = "bevy_render"

[[types]]
type = "PerspectiveProjection"
source = "bevy_render"

[[types]]
type = "CameraRenderGraph"
source = "bevy_render"


## BEVY_UTILS
# needs a reflect impl
# [[types]]
# type="Uuid"
# source="uuid"

## BEVY_ASSET

[[types]]
type = "AssetPathId"
source = "bevy_asset"

[[types]]
type = "LabelId"
source = "bevy_asset"

[[types]]
type = "SourcePathId"
source = "bevy_asset"

[[types]]
type = "HandleId"
source = "bevy_asset"

## BEVY_MATH
[[types]]
type = "Vec2"
source = "bevy_math"
import_path = "glam::f32::Vec2"

[[types]]
type = "Vec3"
source = "bevy_math"
import_path = "glam::f32::Vec3"

[[types]]
type = "Vec3A"
source = "bevy_math"
import_path = "glam::f32::Vec3A"


[[types]]
type = "Vec4"
source = "bevy_math"

import_path = "glam::f32::Vec4"

[[types]]
type = "BVec2"
source = "bevy_math"
import_path = "glam::bool::BVec2"

[[types]]
type = "BVec3"
source = "bevy_math"
import_path = "glam::bool::BVec3"

[[types]]
type = "BVec4"
source = "bevy_math"
import_path = "glam::bool::BVec4"

[[types]]
type = "BVec3A"
source = "bevy_math"
import_path = "glam::bool::BVec3A"

[[types]]
type = "BVec4A"
source = "bevy_math"
import_path = "glam::bool::BVec4A"

[[types]]
type = "DVec2"
source = "bevy_math"

import_path = "glam::f64::DVec2"

[[types]]
type = "DVec3"
source = "bevy_math"

import_path = "glam::f64::DVec3"

[[types]]
type = "DVec4"
source = "bevy_math"

import_path = "glam::f64::DVec4"

[[types]]
type = "IVec2"
source = "bevy_math"

import_path = "glam::i32::IVec2"

[[types]]
type = "IVec3"
source = "bevy_math"

import_path = "glam::i32::IVec3"

[[types]]
type = "IVec4"
source = "bevy_math"

import_path = "glam::i32::IVec4"

[[types]]
type = "UVec2"
source = "bevy_math"

import_path = "glam::u32::UVec2"

[[types]]
type = "UVec3"
source = "bevy_math"

import_path = "glam::u32::UVec3"

[[types]]
type = "UVec4"
source = "bevy_math"

import_path = "glam::u32::UVec4"

[[types]]
type = "Mat3"
source = "bevy_math"

import_path = "glam::f32::Mat3"

[[types]]
type = "Mat2"
source = "bevy_math"
import_path = "glam::f32::Mat2"


[[types]]
type = "Mat3A"
source = "bevy_math"
import_path = "glam::f32::Mat3A"

[[types]]
type = "Mat4"
source = "bevy_math"
import_path = "glam::f32::Mat4"


[[types]]
type = "DMat2"
source = "bevy_math"
import_path = "glam::f64::DMat2"

[[types]]
type = "DMat3"
source = "bevy_math"
import_path = "glam::f64::DMat3"

[[types]]
type = "DMat4"
source = "bevy_math"
import_path = "glam::f64::DMat4"

[[types]]
type = "Affine2"
source = "bevy_math"
import_path = "glam::f32::Affine2"

[[types]]
type = "Affine3A"
source = "bevy_math"
import_path = "glam::f32::Affine3A"

[[types]]
type = "DAffine2"
source = "bevy_math"
import_path = "glam::f64::DAffine2"

[[types]]
type = "DAffine3"
source = "bevy_math"
import_path = "glam::f64::DAffine3"

[[types]]
type = "Quat"
source = "bevy_math"
import_path = "glam::f32::Quat"

[[types]]
type = "DQuat"
source = "bevy_math"
import_path = "glam::f64::DQuat"

[[types]]
type = "EulerRot"
source = "bevy_math"
import_path = "glam::EulerRot"

[[types]]
type = "Rect"
source = "bevy_math"
